services:
  eureka-server:
    container_name: book-eureka-server
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: ${EUREKA_SERVER_JAR}
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
      SPRING_BOOT_ADMIN_URL: http://admin-server:8082
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8761/health | grep UP || exit 1"
      interval: 10s
      retries: 15
      start_period: 30s
      timeout: 10s
    ports:
      - '8761:8761'

  artemis-broker:
    container_name: book-artemis-broker
    image: apache/activemq-artemis:latest
    ports:
      - '61616:61616'
      - '8161:8161'
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis
      ARTEMIS_CREATE_ARGS: "--force"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8161/console" ]
      interval: 10s
      retries: 15
      start_period: 30s
      timeout: 10s

  api-gateway:
    container_name: book-api-gateway
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: ${API_GATEWAY_JAR}
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
      SPRING_BOOT_ADMIN_URL: http://admin-server:8082
    ports:
      - '8080:8080'
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8080/health | grep UP || exit 1"
      interval: 10s
      retries: 15
      start_period: 20s
      timeout: 10s
    depends_on:
      eureka-server:
        condition: service_healthy

  main-service:
    container_name: book-main-service
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: ${MAIN_SERVICE_JAR}
    ports:
      - '8072:8072'
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
      ARTEMIS_URL: tcp://artemis-broker:61616
      SPRING_BOOT_ADMIN_URL: http://admin-server:8082
    depends_on:
      authentication-service:
        condition: service_healthy
      artemis-broker:
        condition: service_healthy

  authentication-service:
    container_name: book-authentication-service
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: ${AUTHENTICATION_SERVICE_JAR}
    ports:
      - '8074:8074'
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
      SPRING_BOOT_ADMIN_URL: http://admin-server:8082
      ARTEMIS_URL: tcp://artemis-broker:61616
    depends_on:
      admin-server:
        condition: service_started
      api-gateway:
        condition: service_healthy
      artemis-broker:
        condition: service_healthy
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8074/health | grep UP || exit 1"
      interval: 10s
      retries: 15
      start_period: 20s
      timeout: 10s

  stats-service:
    container_name: book-stats-service
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: ${STATS_SERVICE_JAR}
    ports:
      - '8068:8068'
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
      SPRING_BOOT_ADMIN_URL: http://admin-server:8082
    depends_on:
      api-gateway:
        condition: service_healthy
      artemis-broker:
        condition: service_healthy

  notification-service:
    container_name: book-notification-service
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: ${NOTIFICATION_SERVICE_JAR}
    ports:
      - '8060:8060'
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
      SPRING_BOOT_ADMIN_URL: http://admin-server:8082
      ARTEMIS_URL: tcp://artemis-broker:61616
    depends_on:
      api-gateway:
        condition: service_healthy
      artemis-broker:
        condition: service_healthy

  admin-server:
    container_name: book-admin-server
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: ${ADMIN_SERVICE_JAR}
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
      SPRING_BOOT_ADMIN_CLIENT_URL: http://admin-server:8082
    ports:
      - '8082:8082'
    depends_on:
      eureka-server:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    depends_on:
      - eureka-server
      - api-gateway
      - main-service
      - authentication-service
      - admin-server

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-storage: