package com.ukma.authentication.service.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

public interface GetUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
