server:
  port: 8068

spring:
  application:
    name: stats-service
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  artemis:
    broker-url: ${ARTEMIS_URL:tcp://localhost:61616}
    user: artemis
    password: artemis
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.jms: DEBUG

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
grpc:
  client:
    authentication-service:
      negotiationType: PLAINTEXT
      address: discovery:///authentication-service

cloudinary:
  cloudName: dbkgbcqcf
  apiKey: '463961816584397'
  apiSecret: VXmTJHTHnvMvW3zg9VsgD0aki9w