server:
  port: 0

spring:
  artemis:
    broker-url: ${ARTEMIS_URL:tcp://localhost:61616}
    user: artemis
    password: artemis
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: authentication-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    enabled: true

management:
  endpoints:
    web:
      base-path: /