server:
  port: 0

spring:
  artemis:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: authentication-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    enabled: true

auth:
  key:
    private: MHcCAQEEIIQg3flfMCXTl7PnGWP1xBOWgRMB/1pMRkN4F61KkaGsoAoGCCqGSM49AwEHoUQDQgAEZ2nwD3R8HJfcHa4qIB95jtCYbdnodH35/RfYI8BDcFKkbUtukBrIVUEbENKXNHc1iWphB7pgcHOqZ7PwIyIRRg==
    public: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEZ2nwD3R8HJfcHa4qIB95jtCYbdnodH35/RfYI8BDcFKkbUtukBrIVUEbENKXNHc1iWphB7pgcHOqZ7PwIyIRRg==
