server:
  port: 8074

spring:
  artemis:
    broker-url: ${ARTEMIS_URL:tcp://localhost:61616}
    user: artemis
    password: artemis
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: authentication-service
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    enabled: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

