server:
  port: 8082

spring:
  application:
    name: admin-server

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    enabled: true

management:
    jmx:
      exposure:
        include: "health"