package com.ukma.stats.service.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
